### ISSUE TITLE
CQLOperatorsBinding.BindConvert() returning Argument Exception for MedicationRequest.status

### ISSUE THREAD

**Issue by dvargaslantana** [FirelyTeam/firely-cql-sdk#129]
Hello,

I'm not sure if this is a bug, but would like to get some feedback on what I'm seeing. 

Attached is a CQL function that returns a MedicationRequest resource. After converting it into ELM and running it through the PackagerCLI, I receive the following error:

![image](https://github.com/FirelyTeam/firely-cql-sdk/assets/116004423/f9164164-b970-4d4e-abe4-795bb1b07764)

The error occurs in CQLOperatorsBinding.BindConvert(), approximately line 752. 

Tracing through the code, it looks like it attempts to determine if it can perform a conversion on MedicationRequest.status prior to the thrown exception. The check returns the conversion type as 'incompatible' because there doesn't appear to be a matching type in the TypeConverter dictionary. 

![image](https://github.com/FirelyTeam/firely-cql-sdk/assets/116004423/162b9668-581d-4089-9749-b4503afecb06)

I've attached a CSV export of any references to 'MedicationRequest' found in the TypeConverter dictionary.

[TypeConverter.csv](https://github.com/FirelyTeam/firely-cql-sdk/files/13504913/TypeConverter.csv)

Just wanted to see if there is a way to resolve the conversion error. Are there additional type references that need to be added to the TypeConverter in CQL.Conversion? Please let me know if any additional information is needed.

Any help would be appreciated!

CQL and Elm files:
[cql_and_elm_example.zip](https://github.com/FirelyTeam/firely-cql-sdk/files/13507807/cql_and_elm_example.zip)

Call stack: 
[call_stack.txt](https://github.com/FirelyTeam/firely-cql-sdk/files/13504916/call_stack.txt)

**Comment by EvanMachusak** [comment]
Daniel-

Thanks for reporting this issue.  I am certain you will encounter additional issues in this vein as you continue to create FHIR resources within CQL, which is a use case we have not thoroughly tested.  CQL best practice is to transform FHIR types to System types as soon as possible and then write all of your CQL defines and functions to operate on System types, not FHIR types.  This will allow your CQL assets to be fungible across different models, e.g. base FHIR, QI Core, even QDM.

The root cause of the problem is that our default type converters don't have full coverage for these use cases.  For example, when you are binding `authoredOn` to `m.authoredOn`, what's happening is that the ELM is identifying `m.authoredOn` as a `{http://hl7.org/fhir}dateTime`, but we're trying to bind this to the `MedicationRequest` class whose `AuthoredOn` property is a `string`.  This is simply because the Firely SDK models all data elements as `string` to account for the (very common) use case where elements can be choice types.

The binder is attempting to make this assignment and it needs to convert `FhirDateTime` to `string`, which is a conversion we did not have specified.

In the event you find more of these conversion misses, you can add them yourself with this code:

```
var converter = FhirTypeConverter.Create(Hl7.Fhir.Model.ModelInfo.ModelInspector);
converter.AddConversion<FhirDateTime, string>(date => date.ToString());
var binding = new CqlOperatorsBinding(TypeResolver, converter);
```

That said, please report the conversions that are missing.  Although it's not ideal to create FHIR resources inline in CQL, it is a valid language construct that we would like to fully support.

**Comment by EvanMachusak** [comment]
See  #131
