### ISSUE TITLE
Performance hit with numerous class initializations (2.0)

### ISSUE THREAD

**Issue by baseTwo** [FirelyTeam/firely-cql-sdk#575]
This is the same ticket as below, only for the 2.0 branch:
- #547

**Comment by ewoutkramer** [comment]
To improve over the 1.0 implementation, we need to make sure that:
 
* If the CQL has only functions in a library, then it should be singleton
* If has defines in it, it should not be singleton.
* We should preserve the lazy behaviour for non-singleton classes.

Put otherwise: we should keep the old situation, except for CQL libraries that only contain CQL functions.

**Comment by ewoutkramer** [comment]
An idea that we discussed was to put the memoization in the CqlContext. This would require you to be smart with the key, since the names of the functions can be aliased etc. We initially used Lazy, since it was faster, and we would need to do perf testing to see whether moving the state to CqlContext is slower.
